### PR TITLE
Latest version from MAC-NW

### PR DESCRIPTION
**Pull request by RottenMind**
Check carefully, there is not too much I added to MAC-NW original, but MAC-NW´s  "sell items" is big change,
- sell T2 enchants/runestones are essential
- tier4 healling potions can be usefull
- sell description and WArnings are needed
- some version history is good keep visible

I will make GreasyFork update when we think this is "safe" and changes will not cause too much confusions.

### CODE REVIEW

**Comment by Phr33d0m** [comment]
There are 2 exactly the same `if(settings["limitskillkits"])`, can you move that to a function and call that function instead?

Also, we should reformat the code to be more reading friendly and stick to using 4 spaces indentation.

**Comment by RottenMind** [comment]
I think MAC-NW do that function or it is better wait to see what UI -changes brings in, some sell option is good to bring on UI.

If you do code  "Reformat", we others then try obey it, is that OK?

**Comment by RottenMind** [comment]
Check that ver. 1.05.0.1k . if you dont allready use it, MAC-NW did good additions on it.

I hope I learned not  spoil formatting, ;).

EDIT, Inventory "Auto Vendor" -button is nice addition and "Sell" -filter is now easy access

.

**Comment by Phr33d0m** [comment]
I've been testing off your repo and looks fine for now (haven't tested much). If we could get @mac-nw to fix those things I commented on I'll merge and release so you can include it on greasyfork too.

Also, let's get rid of that awful versioning too :-). Next release will be 1.6.0, sounds good?

**Comment by Phr33d0m** [comment]
I fixed the Potion_Potion_... thingy, fixed the indentation (it's set on Tabulation character which is easier to work with) and merged.

**Comment by RottenMind** [comment]
Well, sell list if  set "skillkits/altars" 0 and sell all potions, keeps trash away.

I used filter /Blue..Unid|Green..Unid/ because I hate sell Unidentified trash.

No for "Event trash" but YES for Profession items filters.

**Pull request merged**
