### PR TITLE
Grayed not active characters

### PR DESCRIPTION
**Pull request by WloBeb**

### CODE REVIEW

**Comment by Phr33d0m** [comment]
~~@WloBeb from what I can see the colour doesn't change if we click the Activate button, right?~~ Nevermind, @noonereally already said it above.

**Comment by noonereally** [comment]
Why not ? 
`$(":focus").parents('.ui-accordion-content').prev().removeClass('inactive');` (at line 2066) 
Should make it back to original color...

**Comment by Phr33d0m** [comment]
True that, didn't notice.

**Comment by WloBeb** [comment]
@noonereally said:
"I think will be better as if (charSettingsList[charName].general.active) you get the char name from the .forEach"

<del>I'm not sure, but I think we have "name@account" as index in charSettingsList array. In this code charName is name of character only. I can't test it now because of maintenance...</del>

This one works...
But <b>$(elm.target)</b> doesn't (elm.target is undefined).
I change this to <b>$("#"+elm.id)</b>

**Comment by noonereally** [comment]
I've rechecked, my mistake, it's `event.target` from a propagated dom event, but I've passed the element itself already and not an event, so actually just `$(elm)`.... should work.
Your way of `:focus` or `$(elm)` if works, should be better, if id is not set they will work.
I'll try `$(elm)` or revert to `:focus` when I can test.

And thanks again for testing and PRing

**Pull request merged**
