### PR TITLE
Mod6 professions.

### PR DESCRIPTION
**Pull request by dlebedynskyi**
I used leadership planer from Phr33d0m as base for leadership.

"Resource/AD" is based on AD profile with focus on chests and reward. Give ~ 25% more.

Added craft profiles  20 till 25 for  Mail smith, Jewel crafting 
Mailsmith is using general tier 3 since all tier 4 require Unified elements that might be an issue to get at first.

### CODE REVIEW

**Comment by noonereally** [comment]
what is the leadership planer ?

**Comment by dlebedynskyi** [comment]
2 profiles for leadership for ad and xp for 20-25. Might need adjustments but good enough for now.

**Comment by dlebedynskyi** [comment]
@BigRedBrent  generally we can create RP profile. At the moment I added general "resources" profile that should be focused on Refine stuff as well. Mostly Im was checking number of chests that are produced on lvl 20 -22. This is the most I got too. In general it makes 25-30% more 'chests' then AD profile.

**Comment by Phr33d0m** [comment]
@dlebedynskyi Thanks for this. I'll check it out and merge it in a couple of days as there's no hurry until 7th of April. 

Anyways, AFAIR all the new rank +20 leadership professions have worse AD/time ratio than what we currently use. Can anyone confirm?

**Comment by noonereally** [comment]
The current leadership task ( <= 20 ) were nerfed by adding time to most of the tasks.
The new tasks at 25 are somewhat comparable to today's 20 in terms of AD/h.

**Pull request merged**
