### PR TITLE
Profile registration simplified. Alchemy hang up fixes

### PR DESCRIPTION
**Pull request by dlebedynskyi**
Alchemy fix for.
https://github.com/Phr33d0m/NW-Profession-Bot/issues/56

Added addProfileToDefined function for profiles extension. Fixed some of Mailsmith sprofles.

Added task_list.js with known tasks name for easier search and mod 6.

### CODE REVIEW

**Comment by Phr33d0m** [comment]
Looks good on first sight, I'll merge it tonight. Thanks.

**Comment by dlebedynskyi** [comment]
added one missing purple item to mailsmithing

**Comment by dlebedynskyi** [comment]
also you might want to update script since 
https://greasyfork.org/en/scripts/7061-neverwinter-gateway-professions-robot is pointing to 1.10.4 by Rotten_mind

**Comment by noonereally** [comment]
This is a very good idea.  (I'm trying to add few things so I've added it manually into my fork)

btw, what ide you are using? I noticed all the functions have no indent even in the $(function () {
scope. and on commit it wont recognize the diff and set -3k lines deleted and +3k added 
But the tabs look ok for you.
I've tried notepad++ but still some things are tabbed incorrectly (even with the tab setting set as spaces) but the indent is not changed.

**Comment by Phr33d0m** [comment]
When editing, don't autoformat the entire code. Just change the lines you
want to edit.

**Comment by dlebedynskyi** [comment]
I might have auto lined it by mistake. Usually using Sublime. But might auto lined it as a habit.

**Comment by dlebedynskyi** [comment]
Are you planning to merge this pull?

**Comment by Phr33d0m** [comment]
Of course I am, but damn it makes my eyes bleed going through all the changes and IIRC you haven't merged it with the latest commit which makes it even harder :-/.

**Comment by dlebedynskyi** [comment]
great release. thanks!

**Pull request merged**
