### PR TITLE
Updates for profiles

### PR DESCRIPTION
**Pull request by dlebedynskyi**
Leatherworking, Mailsmiting, Jewelcrafting. Small tweaks for Alchemy

### CODE REVIEW

**Comment by Phr33d0m** [comment]
Please stop using whatever editor you're using. Use Notepad++ with autoformatting turned off or something.

**Comment by dlebedynskyi** [comment]
Gosh. This is merged file. Merged on top yours. OPEN 2ee2181 and see yourself. Even git is saying this can merged automatically. Also advice - use sublime text without any formating.

**Comment by Phr33d0m** [comment]
~~I'm not complaining because it's not mergeable, but because it has a hugeload of unnecessary lines (random spaces added by your editor) I have to go through to see only the 10 lines you've really changed - and that's a hassle. And just because someone was too lazy to configure their editor to not unnecessarly mess with the code.~~

~~Also, through the years I've learnt to never trust github on if a file is mergeable - the system could be able to merge it but the result won't be the expected one.~~

Whatever, thanks for the changes.

**Comment by dlebedynskyi** [comment]
you are welcome. I specifically updated on top of yours to avoid any possible issues with spaces ets and to make sure that my changes are only on required part. 
I was a pain to merge your top master in  2ee2181 on top of yours from last tag and keep correct changes at right places too.

**Comment by Phr33d0m** [comment]
> to avoid any possible issues with spaces

If you go through the diff you can see that 50% of it are just useless space changes, anyways.

**Pull request merged**
