### PR TITLE
Translation support

### PR DESCRIPTION
**Pull request by WloBeb**
Additional setting - "language"
For now only first tab - "General Settings" - possible to translate.
First tab translated to polish :D

### CODE REVIEW

**Comment by Phr33d0m** [comment]
I think the `addTranslation()` and `tr()` functions are completely unnecessary. As I mentioned, isn't it incredibly simpler to just use a static global object?

**Comment by WloBeb** [comment]
I decided to add function addTranslation(), just to move this potentialy very big object to the end of script.
Look at tr() - it checks for spelling errors, and automatically selects the untranslated texts.If someone wants to translate new text, have only to add it to 'en' property, for the rest of translations  warning appears about untranslated text with key of this text (It could be shown the original text - this is a matter to be negotiated). And this is definitely an advantage over static global object.
BTW. look at <a href=https://github.com/Phr33d0m/NW-Profession-Bot/issues/91#issuecomment-101792738>this comment</a> from @noonereally.

**Comment by noonereally** [comment]
I agree, having this at the bottom is a huge advantage.
Having a function in advance to filter things wont hurt, and can accommodate future changes more easily.

More so, probably should move the trackResources, toollist, and worker lists to the bottom same way.

**Comment by WloBeb** [comment]
And addProfile too... (All use of this function, not necessarily a definition).

**Comment by WloBeb** [comment]
@noonereally said "More so, probably should move the trackResources, toollist, and worker lists to the bottom same way."
You can do it even easier: <pre><code>var worker = workerDefinition();</code></pre> 
in current location.
And 

<pre><code>function workerDefinition() {
    return {
        ......    copy of current definition .....
    }
};</code></pre> 

somewhere at the end...

**Comment by noonereally** [comment]
Great idea, and I've already implemented it (local work copy)

**Comment by GeneralSheppard** [comment]
Working on the french version.

**Pull request merged**
