### PR TITLE
Replace defaultTasklist with tasklist

### PR DESCRIPTION
**Pull request by BigRedBot**
Replaced defaultTasklist with tasklist so that they it will always be refreshed when loaded instead of using a previously saved version.

### CODE REVIEW

**Comment by Phr33d0m** [comment]
You're going in the right direction. Now remove any tasklist related gm_setvalue/getvalue (as it's completely useless) and it'll be ready to merge.

**Comment by David3412** [comment]
While that fix is easy to implement it eliminates the infrastructure that looks like it was designed to accommodate customizable task lists. I know I am new to looking at this script but I would not advise completely eliminating all that infrastructure as it will hinder any future efforts to develop a GUI for modifying the task list.

As I said in my original post, this was only meant as a temporary fix and there is a good reason to keep a non-hard coded copy of the tasklist.

**Comment by David3412** [comment]
Although I guess gm_setvalue/getvalue is not that hard to re-implement if I or others ever get to implementing the GUI so it's probably not a big deal.

**Comment by Phr33d0m** [comment]
> Do you mean remove calls to GM_setValue like that?

Best would be to also remove any traces of `charSettings["tasklist" + num]` whenever is used in favor of using the hardcoded tasklist directly.

**Comment by mac-nw** [comment]
I'm running this with out any problems so far.

**Comment by mac-nw** [comment]
Can confirm that my old saved tasks for alchemy was reset to the default list tasks as expected

**Pull request merged**
