### PR TITLE
ZAX Banker Withdraw Fix

### LINKED ISSUE #62: ZAX Consolidation skips and jumps
I've noticed that it pulls the AD from ZAX on random characters even when there is one request and not on the banker.

Also same problem:
https://greasyfork.org/en/forum/discussion/3223/x  (at bottom)

### PR DESCRIPTION
**Pull request by BigRedBot**
Implemented zax banker withdraw fix https://github.com/Phr33d0m/NW-Profession-Bot/issues/62

### CODE REVIEW

**Comment by WloBeb** [comment]
Are you sure it works?
In my opinion we have 2 problems:
1. to short delay betwen canceling offer and withdraw.
2. in lines 4091-4094 

<pre>        var exchangeDiamonds = parseInt(unsafeWindow.client.dataModel.model.exchangeaccountdata.readytoclaimescrow);
        if (exchangeDiamonds > 0) {
            claimZexOffer();
        }</pre>

If banker cancels offers but fails to withdraw, the next character withdraws AD and create new offer.
Then banker cancels this offer but fails to withdraw, and again and again. 
I think I found solution but I have to test it.

**Comment by WloBeb** [comment]
I think that none of your proposal will work, because claimZexOffer() inside withdrawZexOffer()  never works. Too small interval between canceling and withdrawing.

**Comment by BigRedBrent** [comment]
It seems to always work for me as long as there is a listing in the exchange before it gets to the character that is processed just before the banker, and that seems to be almost always.

**Comment by BigRedBrent** [comment]
Have you tested this and seen if it works? It always works for me, and counts the ad correctly. I don't know why, but your proposed solution does not count the ad correctly.

**Comment by WloBeb** [comment]
I tested several different solutions.
And banker always just canceled offers (when call withdrawZexOffer()) but never withdrew anything.
Because of "if" in line 4092 next character always saw canceled offer, withdrew AD and ... created new offer. And everything was repeated.
It should probably work if you connect both your commits eg.
1. call withdrawZexOffer() at the beginnig (for banker)
2. call claimZexOffer() (or again withdrawZexOffer()) somewhere later

If you see my pull request, you probably know, that I'm doing just that.
Banker always call withdrawZexOffer()  (which only cancel offers), then select new tasks and at the end 
call claimZexOffer() which move AD to his personal balance.

**Comment by WloBeb** [comment]
Now I notice where the code has been added - the processing of the <b>previous</b> person, and after finding that the <b>next one</b> will be the banker. If you wrote it, I would have noticed.
So YES, it should work. 
We should probably for sure remove call to claimZexOffer(); from inside withdrawZexOffer(), that does nothing.
@noonereally please merge #69 pull request.

**Pull request merged**
