### PR TITLE
Checking diff

### PR DESCRIPTION
**Pull request by noonereally**

### CODE REVIEW

**Comment by noonereally** [comment]
A technical question, how I can merge it now (even to my fork), diff goes crazy...

**Comment by Phr33d0m** [comment]
Thanks for making my life easier and merging the latest master changes.

I went through some of the changes and it looks good, quite a bit of new stuff and I like that.

**Comment by noonereally** [comment]
Merged everything, looks ok, i'll finish the tools panel and manual task slots control at later time.
Testing / Feedback is welcome.

**Comment by noonereally** [comment]
- Added more menu options for Skip "Patrol the Mines" to allow more flexability (Until per char options implemented).
- Better use of leadership assets (white used only if heros, adventurers & man-at-arms to low). WloBeb
- Added overview tabs for profession levels and profession slots
- More info in the Counter Tab
- Added Resources overview
- Added Profession assets overview tabs (needs more work)
- Moved more statistics gathering into JSON object and added per char name settings load
- Added "Load Character Names" button and reset settings button
- Separated vendoring of altars and node kits
- Initial structures for JSON settings
- UI added for manual slot task allocations (Only the UI, but probably will finish it when the gateway will work)

**Comment by Phr33d0m** [comment]
Sorry but I gave up on trying to solve all the conflicts. Some of your changes are very drastic and I'm not sure if that's what you intended to do or it's just my diff checker on drugs today.

Could you do me the favor and merge it with the latest commits from `master` please?

**Comment by Phr33d0m** [comment]
@noonereally ping. Any help on merging this?

**Comment by noonereally** [comment]
I don't know how to make github accept it. I've merged manually (diff) 12 days ago, and last change was 14 days ago so should be ok, but better to double check.

I've opened the pull request to see the diffs (it didn't work), the changes are work in progress, and has some stuff that don't work (the manual slot selection tab).

**Comment by Phr33d0m** [comment]
Okay I've manually merged (copy/pasted) your work over the one in `master`. For any further work please re-fork and work over that. Thanks for all the awesome work you've done :-).

**Comment by noonereally** [comment]
I've reopened and committed  a copy paste (no changes) but it will sync the fork, so it will not be ahead and prevent further conflicts. (I hope)

**Comment by noonereally** [comment]
btw, did you use some sort of auto formatting tool ?  some of the arrays like settings are all 'expanded' and it looks weird.

**Comment by Phr33d0m** [comment]
@noonereally I copy/pasted your repo's `main.js` directly from github's editor to github's editor. Feel free to adjust any strange formatting the editor might have added... Duh, stupid editors.

**Pull request merged**
