### PR TITLE
TaskList with profiles per taskname,  priority per taskname, accordion char selection.

### PR DESCRIPTION
**Pull request by noonereally**
Working variation with profiles per each task type and a priority.
Also added Accordion and tabs to each char.

even if not merged, perhaps it will be useful for future updates

### CODE REVIEW

**Comment by RottenMind** [comment]
This "mod" gives good example for "Easy tasklist edit", with it editing multiple characters tasklist is easy.

...but it makes script editing harder to understand so "Prebuild" options became more necessary.

**Comment by noonereally** [comment]
The idea is that users can add profiles only, never touching the tasks settings. 
For example. you want a profile that makes potions for alchemy, no problem add one, and it wont change any existing tasks.

**Comment by RottenMind** [comment]
Yes, I think I got it... maybe we need add button "Do it for me, I dont understand" or similar and after button is checked, script levels one profession up to 20, start leadership, sells items for gold and start Alchemy and so on... untill you have 3x prof. level20 then all free slots goes for leadership by default.... xD

**Comment by RottenMind** [comment]
I use this for test only,
- Alchemy test subject

https://github.com/RottenMind/NW-Profession-Bot/commit/6e01601c43b4eaeb4b21b2b780bb1f1b8d68431a

It seems that "limit 10" items not to sell is too low, sell items limits must craft for per PRofession what has good ability to level without residuum
- Alchemy
- Platesmithing
- Mailsmithing

It will be easy to add them to main script after test, Jewelcrafting what I started is slow and its good only if you have personal use for it, IMHO.

**Comment by RottenMind** [comment]
I used this "sample" UI to test multiple tasklist and ended up to Full Automated Alchemy leveling, only slots must be added by user.
https://github.com/RottenMind/NW-Profession-Bot/commit/6e01601c43b4eaeb4b21b2b780bb1f1b8d68431a
(best way to test this is make account to RU server, allmost 100% proof that you cant  transfer any items for your account and AH use is "interesting", до свидания )

_You did some research for "autofill non used slots", can you open "branch" for it and if it can see new slot maybe it can also detect,_
- _leadership 5x slot_
- _tailoring 1x slot_
- _Alchemy 4x slot_

_, failures, I think it is quite common failure..._ ;)

Concept to handling multiple tasklist is good with this, adding tasklist is confusing(in script), switching them is fun (when some one is done them for you).

Now just look what comes next.

**Comment by Phr33d0m** [comment]
Please fix any conflicts with the latest changes in the master branch. Then I'll commit it to a dev branch dedicated to UI improvements.

**Comment by RottenMind** [comment]
I check difference between this build/Greasyfork ver. 1.10.4/Mod6 test1.10.14/Github current build and make one new for testing. I still dont get "slot priority", but maybe it makes sense one day...

Mod6 changes professions little and if you can easily switch between different tasklist then it is easier handle. Testing Mod6 professions with old UI is useless and painful...

**Comment by noonereally** [comment]
The priority is a solution to @BigRedBrent suggestion/commit. The script will allocate empty slots based on the priority. 
This way, you can set more than 9 (or the number of slots available) total tasks.
For example, you set 9 leadership on low priority, you want to add alchemy or there is event going you set them to high priority without changing the leadership number and they will be allocated.
Another good example is new characters that get slots opened as they level, you put 9 leadership and 1 alchemy but alchemy on higher priority and the alchemy will be always done and more and more leadership slots will be allocated as they open.

That makes the task order cosmetic only
more info:
https://github.com/Phr33d0m/NW-Profession-Bot/pull/18

**Comment by noonereally** [comment]
btw, Iv'e checked with diff the code and it should have all the changes, also added tabs for the upper settings part, a 'hack' until something better done and settings is restructured.
I needed room to add RefinedAD counters, so i used tabs for now.

I do not know what to do with the merge conflict..

**Comment by RottenMind** [comment]
@noonereally , OK about slot, it was Brent who did some tampering with slots, but he told that it wont work as he wanted, maybe something is changed.

It is still long time to Mod6, where multiple tasklist are really needed so have time to tamper.

**Comment by noonereally** [comment]
You missed the point, the priority is so it will work like he wanted without tempering with the slot order.
Just put more than 9 **total** slots and play with priority, you will see what it does.

**Comment by RottenMind** [comment]
Something is rotten with, (tested with your current build, my own build, same results)
- mailsmithing
- platesmithing

I started testing all profession rotation and two of them gives me error,

---

Selling 1 Crafted_Med_Armorsmithing_Chain_Armor_1 to vendor.
VM42373:1255 Looking for empty slots.
VM42373:1260 Prioritizing task lists.
VM42373:1265 Attempting to fill the slot.
VM42373:1399 Uncaught TypeError: Cannot read property 'level' of undefined

---

I look it closer... but if you see what may cause it please do so.

**Comment by noonereally** [comment]
fixed

**Comment by RottenMind** [comment]
I have final question for "Priority" change what currently seems solve "opens slot issues causesd by usersr",

+ can you make it see "Black Ice refining" failure or is this issue allready solved?
,nah anyway, I try check worst case scenarios with my "gather-sell" solution... just few accout upt tens,...

**Comment by RottenMind** [comment]
It started crash today, will test later... AFK few days or weeks. XD

Rolled back earlier version of this, no big deal, ;).

**Comment by Phr33d0m** [comment]
Okay I'm back. What's the status on this @noonereally? Can we merge it or there are pending issues with it and that's why you closed it?

**Comment by dlebedynskyi** [comment]
His UI is pretty good. I created some sample profiles for crafting profs. works nice by just switching your profile

**Comment by noonereally** [comment]
I'm using it now, and know of some others. No one replayed here for long time so i closed after a while.

**Pull request merged**
