### PR TITLE
Manual Mode

### PR DESCRIPTION
**Pull request by HenryLoenwind**
In manual mode the script will stop when encountering a Leadership task.

The user is notified with a text message and a sound. After a while the script will go ahead and continue looking for (non-Leadership) tasks for that slot. The user can also tell the script to continue manually.

There are config settings for:
- The time the user is given to manually assign a task
- The time before the script re-arms after a timeout
- The volume of the notification sound (including "off")

This mode is enabled and disabled with a button besides the pause button.

Note: For this to work, Leadership has to have a higher priority than other professions. If the script finds any non-Leadership task to start, it will do so.

Source of the sound: Project "ion.sound" on Github (MIT licence)

### CODE REVIEW

**Comment by HenryLoenwind** [comment]
Update:

There are two buttons on the notification: "Ignore" tells the script to ignore Leadership and assign another task. "Done" tells it to re-scan the tasks because the user manually assigned a Leadership task.

Someone probably should css them up a bit so they look like buttons, btw.

Update 2: Added a new config tab with a description on how to use this.

**Comment by noonereally** [comment]
Nice. 
I just tried it briefly, and a small thing, I think the timer reset from the SCA&Visit tabs no longer works.
And the buttons ;) 
Unfortunately, I can't help much with the css button thing, maybe just Jquery.button() it ? at least for now so it's clearer that it's clickable.

**Comment by HenryLoenwind** [comment]
Thx.

I didn't change anything about those reset buttons (other than copy their code ;) ), I used them extensively while testing my coding (getting an open slot is easiest done by cancelling a task), and I just retested them. Works fine for me.

**Comment by noonereally** [comment]
You are right, my bad, I forgot about the added random time and didn't wait it when tested.
Probably should set it as an option.

**Pull request merged**
