### PR TITLE
Extra asset FIX

### PR DESCRIPTION
**Pull request by RottenMind**
Fix BUG extra assets selects workers when need select tools.
- extra asset selection strings "Tools", "Tool"

Affets LEatherworking Tailoring, needs testing and check!

### CODE REVIEW

**Comment by RottenMind** [comment]
Tools selection is still act wierd way, working with
- TAiloring(tested BUG fix)
- ALchemy (tested)
- Leatherworking (tested BUG fix)
- Jewelcrafting (tested)

other professions needs check.

**Comment by Phr33d0m** [comment]
Looks good thanks. Btw, there's no need to add 'editted/added by <X>' anymore, github tells us who added what line and when.

**Comment by RottenMind** [comment]
It ends in Greasyfork and there we dont know who did and what, so adding those items serve "Forkers". 

Github is good place because it forgive, Greasyfork is not that easy.

**Comment by Phr33d0m** [comment]
Greasyfork is just for the pull-and-run. Currently, contributing should only be done via github and here we know who commits what. In production (i.e. greasyfork), it doesn't matter to the user who commited what :-)

**Pull request merged**
