### PR TITLE
Translation again :)

### PR DESCRIPTION
**Pull request by WloBeb**
- script settings & general settings again
- tabs translate again
- one serious bug repaired

### CODE REVIEW

**Comment by noonereally** [comment]
Thanks, and sorry, I got the previous work 'deleted'.

**Comment by Phr33d0m** [comment]
Out of curiousity, what was the serious bug you fixed?

**Comment by WloBeb** [comment]
look closer - missing semicolon at line 4340 :) which could lead to script crash :( It happend once to me...
I wonder how @noonereally tested this code. Probably the error occurred at copy-paste or manually merged operations.

**Comment by Phr33d0m** [comment]
Missing semicolon? You should recheck your javascript books :-P hehe.

**Comment by WloBeb** [comment]
@Phr33d0m Do you really think that this code (without ;) is correct?<code><pre>console.log("Reseting for " + charNamesList[value-1])
chartimers[parseInt(value)-1] = null;</pre></code>All my books of JavaScript said: "JavaScript statements are separated by semicolons". Maybe ASI fix this code, but I'm not sure...

**Comment by Phr33d0m** [comment]
@WloBeb it is perfectly correct and will work just fine. The problem comes when you try to do fancy stuff with the code (e.g. obfuscation or whatever) that's probably why your books tell you so, although in any case - it's not obligatory (just good practice(?)). The best article I could find about it is [this one](http://mislav.uniqpath.com/2010/05/semicolons/).

**Comment by WloBeb** [comment]
As I said before: it's probably because of ASI - Automatic Semicolon Insertion. JavaScript interpreter try to determine where to insert semicolon at the end of line, before (or during) script execution. But <b>I don't like any automation</b> (unnecessary in my opinion) in um... programming.

**Comment by noonereally** [comment]
Hmmm I always thought it was mandatory, and I am surprised it worked, I test briefly before I upload.
Well, learned new thing.

**Comment by Phr33d0m** [comment]
@WloBeb correct. I don't like it either. In any case, if you don't do fancy stuff (from the link I posted above) - no semicolons at all will make it work 99% of the time, yet personally no semicolons makes my eyes bleed (that's why I don't like Python!!) :-P.

**Pull request merged**
